SELECT 
    * 
FROM SNOW_DB.PUBLIC.FIGHTERS
    JOIN SNOW_DB.PUBLIC.EVENTS
        ON FIGHTERS.NEXT_EVENT_ID = EVENTS.ID
    JOIN SNOW_DB.PUBLIC.LOCATIONS
        ON FIGHTERS.LOCATION_ID = LOCATIONS.ID
