SELECT 
    FIGHTERS.ID,
    -- FIGHTERS.LOCATION_ID,
    -- FIGHTERS.NEXT_EVENT_ID,
    FIGHTERS.NAME,
    FIGHTERS.SURNAME,
    FIGHTERS.WEIGHT_CATEGORY,
    FIGHTERS.RANK,
    -- EVENTS.ID,
    EVENTS.NAME as "EVENT NAME",
    EVENTS.CITY as "EVENT CITY",
    -- LOCATIONS.ID,
    LOCATIONS.CITY as "HOMETOWN",
    LOCATIONS.COUNTRY as "HOMECOUNTRY"
FROM SNOW_DB.PUBLIC.FIGHTERS
    JOIN SNOW_DB.PUBLIC.EVENTS
        ON FIGHTERS.NEXT_EVENT_ID = EVENTS.ID
    JOIN SNOW_DB.PUBLIC.LOCATIONS
        ON FIGHTERS.LOCATION_ID = LOCATIONS.ID
